### ISSUE TITLE
moonlight will silently fail to load when given an invalid devSearchPaths entry

### ISSUE THREAD

**Issue by floppydiskette** [moonlight-mod/moonlight#34] opened 2024-02-03 08:20 UTC
if the moonlight config json file contains an entry such as the following
```json
"devSearchPaths": [
    "/path/that/does/not/exist"
]
```
then the discord client seemingly loads normally, but without moonlight enabled. because of this, it can be hard to trace the origin of moonlight failing to load, and thus may not be a desired feature.

may be related to #25, likely not very high priority of an issue

**Comment by Cynosphere** [comment] 2024-02-10 23:29
Duplicate of #30

**Closed by Cynosphere** 2024-02-10 23:29 UTC
